### ISSUE TITLE
Can this be implemented with a certificate not from apple? Say a real SSL certificate, or perhaps a self-signed cert?

### ISSUE THREAD

**Issue by tiagosiebler** [jerrykrinock/CocoaPrivilegedHelper#3]

**Comment by jerrykrinock** [comment]
Hello, tiago.  Thank you for the question.  The answer is "no".  This project does not use certificates in any way.  It was about elevating privileges.  Also, I've just added a heading to the ReadMe to indicate that this is legacy code and should no longer be used.

**Comment by tiagosiebler** [comment]
I thought code-signing was needed for this to work, hence the question whether this would only work with official certs. Thanks for the legacy warning and response either way!
